services:
  postgres:
    image: postgres:15
    container_name: modelbench_postgres
    environment:
      POSTGRES_USER: modelbench
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modelbench
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  inference:
    build:
      context: ./inference
    ports:
      - "9000:9000"
  
  orchestrator:
    build:
      context: ./orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - inference
  
  prometheus:
    image: prom/prometheus:latest
    container_name: modelbench-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - orchestrator

  grafana:
    image: grafana/grafana-oss:latest
    container_name: modelbench-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafana-data:
