services:
  db:
    image: postgres:15
    container_name: modelbench_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: modelbench
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modelbench
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
