services:
  postgres:
    image: postgres:15
    container_name: modelbench_postgres
    environment:
      POSTGRES_USER: modelbench
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modelbench
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  orchestrator:
    build:
      context: ./orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - inference

  inference:
    build:
      context: ./inference
    ports:
      - "9000:9000"

volumes:
  pgdata:
